config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount PgHero::Engine, at: :pghero
  mount ActionCable.server => '/cable'

  namespace :admin do
    root 'users#index'
    resources :users, except: %i(show)
    resources :admins, except: %i(show)
  end

  namespace :api do
    namespace :v1 do
      resources :key_exchanger, only: [] do
        collection do
          get  :get_public
          get  :verify_shared_key
          post :send_public
        end
      end

      resources :users, only: %i[index create] do
        collection do
          post :auth
          put  :update
          post :device_token
        end
      end

      resources :chat_messages, only: %i[index] do
        collection do
          get :chat_list
        end
      end
    end
  end
end

app/views/admin/nav/_assembled.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= admin_root_path %>">Административная панель</a>
  </div>

  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <%= link_to("#{fa_icon 'sign-out fw'} Logout".html_safe, destroy_admin_session_path, :method => :delete) %>
        </li>
      </ul>
    </li>
  </ul>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <a href="<%= admin_admins_path %>"><i class="fa fa-table fa-fw"></i> Администраторы</a>
        </li>
        <li>
          <a href="<%= admin_users_path %>"><i class="fa fa-table fa-fw"></i> Пользователи</a>
        </li>
        <li>
          <a href="<%= new_admin_user_path %>"><i class="fa fa-plus fa-fw"></i> Добавить пользователя</a>
        </li>
      </ul>
    </div>
  </div>
</nav>