config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount PgHero::Engine, at: :pghero
  mount ActionCable.server => '/cable'

  namespace :admin do
    root 'users#index'
    resources :users, except: %i(show)
    resources :admins, except: %i(show)
  end

  namespace :api do
    namespace :v1 do
      resources :key_exchanger, only: [] do
        collection do
          get  :get_public
          get  :verify_shared_key
          post :send_public
        end
      end

      resources :users, only: %i[index create] do
        collection do
          post :auth
          put  :update
          post :device_token
        end
      end

      resources :chat_messages, only: %i[index] do
        collection do
          get :chat_list
        end
      end
    end
  end
end

app/views/admin/admins/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Смена пароля администратора</h1>
  </div>
</div>

<%= bootstrap_form_for [:admin, current_admin] do |f| %>
    <%= f.email_field :email, label: 'Почта' %>
    <%= f.password_field :password, label: 'Пароль' %>
    <%= f.password_field :password_confirmation, label: 'Пароль (повторно)' %>
    <%= f.submit 'Обновить', class: 'btn btn-success' %>
<% end %>

app/views/admin/admins/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Администраторы</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">

    <div class="panel panel-default">
      <div class="panel-heading">
        Список пользователей
      </div>
      <div class="panel-body">
        <table width="100%" data-source="<%= admin_admins_path(format: :json)%>"
               class="table table-striped table-bordered table-hover" id="UsersDataTables">
          <thead>
            <tr>
              <th>ID</th>
              <th>Почта</th>
              <th>IP</th>
              <th>Создан</th>
              <th>Обновлен</th>
              <th>Управление</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</div>